name: atlas-cmms
services:
  postgres:
    image: postgres:16-alpine
    container_name: atlas_db
    environment:
      POSTGRES_DB: atlas
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: quardles
    ports:
      - "4432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    image: intelloop/atlas-cmms-backend
    container_name: atlas-cmms-backend
    depends_on:
      - postgres
      - minio
    environment:
      DB_URL: postgres/atlas
      DB_USER: atlas
      DB_PWD: quardles
      PUBLIC_API_URL: ${PUBLIC_API_URL:-http://localhost:8070}
      FASTSPRING_PWD: ${FASTSPRING_PWD}
      FASTSPRING_USER: ${FASTSPRING_USER}
      PUBLIC_FRONT_URL: ${PUBLIC_FRONT_URL}
      GCP_BUCKET_NAME: ${GCP_BUCKET_NAME}
      GCP_JSON: ${GCP_JSON}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      MAIL_RECIPIENTS: ${MAIL_RECIPIENTS}
      SMTP_PWD: ${SMTP_PWD}
      SMTP_USER: ${SMTP_USER}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_BUCKET: atlas-bucket
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      STORAGE_TYPE: ${STORAGE_TYPE:-minio} #gpc|minio
      PUBLIC_MINIO_ENDPOINT: ${PUBLIC_MINIO_ENDPOINT:-http://localhost:9000}
      INVITATION_VIA_EMAIL: ${INVITATION_VIA_EMAIL:-false}
      ENABLE_EMAIL_NOTIFICATIONS: ${ENABLE_EMAIL_NOTIFICATIONS:-false}
    ports:
      - "8070:8080"
  frontend:
    image: intelloop/atlas-cmms-frontend
    container_name: atlas-cmms-frontend
    environment:
        API_URL: ${PUBLIC_API_URL}
        GOOGLE_KEY: ${GOOGLE_KEY:- }
        GOOGLE_TRACKING_ID: ${GOOGLE_TRACKING_ID:- }
        MUI_X_LICENSE: ${MUI_X_LICENSE:- }
        INVITATION_VIA_EMAIL: ${INVITATION_VIA_EMAIL:-false}
        CLOUD_VERSION: false
        NODE_ENV: production
    ports:
      - "3200:3000"
    depends_on:
      - api
  minio:
    image: minio/minio
    container_name: atlas_minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --address ":9000" --console-address ":9001" /data

volumes:
  postgres_data:
  minio_data:
